### ISSUE TITLE
Actividad2_operaciones

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-AlynGomez12#1]
Alyn Ximena Gomez Hernandez 

[practica individual_ALYN2.pdf](https://github.com/user-attachments/files/16860101/practica.individual_ALYN2.pdf)

**Comment by LenninGS-0** [comment]
Portada: 25/25
Procedimiento:25/25
Figuras, ilustraciones y fotografías: 25/25
Resultados y conclusiones : 25/25
Total: 100

**Comment by josealfredo79** [comment]
Bien hecha revisado..
